services:
  springboot:
    image: challenge-java
    container_name: challenge
    ports:
      - "8088:8080"
    environment:
      DBNAME: db_challenge_java
      DBUSER: ejemplo
      DBPASS: root
      DBHOST: un-mysql
    depends_on:
      - mysql-development
    restart: unless-stopped
  mysql-development:
    image: mysql:5.7
    container_name: un-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: db_challenge_java
      MYSQL_USER: ejemplo
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "42333:3306"
    volumes:
      - "../mysql-volume:/var/lib/mysql"
    restart: unless-stopped