services:
  springboot:
    image: challenge-java
    container_name: challenge
    ports:
      - "8088:8080"
    environment:
      SPRING_CONFIG_NAME: application-example
      DBNAME: db_challenge_java
      DBUSER: ejemplo
      DBPASS: root
      DBHOST: un-mysql
      DBPORT: 3306
      CHHOST: redis
      CHPORT: 6379
    depends_on:
      - mysql-development
      - redis
    restart: unless-stopped
  mysql-development:
    image: mysql:5.7
    container_name: un-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: db_challenge_java
      MYSQL_USER: ejemplo
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "42333:3306"
    volumes:
      - "../mysql-volume:/var/lib/mysql"
    restart: unless-stopped
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"